# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Landmark.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Coordinates_pb2 as Coordinates__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Landmark.proto',
  package='referencepoint.proto',
  syntax='proto3',
  serialized_options=_b('\n\030com.referencepoint.proto'),
  serialized_pb=_b('\n\x0eLandmark.proto\x12\x14referencepoint.proto\x1a\x11\x43oordinates.proto\"\xae\x02\n\x08Landmark\x12\x33\n\x08location\x18\x01 \x01(\x0b\x32!.referencepoint.proto.Coordinates\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x39\n\x04type\x18\x03 \x01(\x0e\x32+.referencepoint.proto.Landmark.LandmarkType\x12\x34\n\tparticles\x18\x04 \x03(\x0b\x32!.referencepoint.proto.Coordinates\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\"Y\n\x0cLandmarkType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04\x44OOR\x10\x01\x12\x18\n\x14HALLWAY_INTERSECTION\x10\x02\x12\n\n\x06STAIRS\x10\x03\x12\x0c\n\x08\x45LEVATOR\x10\x04\x42\x1a\n\x18\x63om.referencepoint.protob\x06proto3')
  ,
  dependencies=[Coordinates__pb2.DESCRIPTOR,])



_LANDMARK_LANDMARKTYPE = _descriptor.EnumDescriptor(
  name='LandmarkType',
  full_name='referencepoint.proto.Landmark.LandmarkType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOOR', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HALLWAY_INTERSECTION', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STAIRS', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ELEVATOR', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=273,
  serialized_end=362,
)
_sym_db.RegisterEnumDescriptor(_LANDMARK_LANDMARKTYPE)


_LANDMARK = _descriptor.Descriptor(
  name='Landmark',
  full_name='referencepoint.proto.Landmark',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='referencepoint.proto.Landmark.location', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='referencepoint.proto.Landmark.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='referencepoint.proto.Landmark.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='particles', full_name='referencepoint.proto.Landmark.particles', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='referencepoint.proto.Landmark.description', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LANDMARK_LANDMARKTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=362,
)

_LANDMARK.fields_by_name['location'].message_type = Coordinates__pb2._COORDINATES
_LANDMARK.fields_by_name['type'].enum_type = _LANDMARK_LANDMARKTYPE
_LANDMARK.fields_by_name['particles'].message_type = Coordinates__pb2._COORDINATES
_LANDMARK_LANDMARKTYPE.containing_type = _LANDMARK
DESCRIPTOR.message_types_by_name['Landmark'] = _LANDMARK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Landmark = _reflection.GeneratedProtocolMessageType('Landmark', (_message.Message,), dict(
  DESCRIPTOR = _LANDMARK,
  __module__ = 'Landmark_pb2'
  # @@protoc_insertion_point(class_scope:referencepoint.proto.Landmark)
  ))
_sym_db.RegisterMessage(Landmark)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
