# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Map.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Building_pb2 as Building__pb2
import Coordinates_pb2 as Coordinates__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Map.proto',
  package='referencepoint.proto',
  syntax='proto3',
  serialized_options=_b('\n\030com.referencepoint.proto'),
  serialized_pb=_b('\n\tMap.proto\x12\x14referencepoint.proto\x1a\x0e\x42uilding.proto\x1a\x11\x43oordinates.proto\"\xd1\x01\n\x03Map\x12\x39\n\x0eminCoordinates\x18\x01 \x01(\x0b\x32!.referencepoint.proto.Coordinates\x12\x39\n\x0emaxCoordinates\x18\x02 \x01(\x0b\x32!.referencepoint.proto.Coordinates\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x31\n\tbuildings\x18\x05 \x03(\x0b\x32\x1e.referencepoint.proto.BuildingB\x1a\n\x18\x63om.referencepoint.protob\x06proto3')
  ,
  dependencies=[Building__pb2.DESCRIPTOR,Coordinates__pb2.DESCRIPTOR,])




_MAP = _descriptor.Descriptor(
  name='Map',
  full_name='referencepoint.proto.Map',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='minCoordinates', full_name='referencepoint.proto.Map.minCoordinates', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maxCoordinates', full_name='referencepoint.proto.Map.maxCoordinates', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='referencepoint.proto.Map.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='referencepoint.proto.Map.description', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buildings', full_name='referencepoint.proto.Map.buildings', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=280,
)

_MAP.fields_by_name['minCoordinates'].message_type = Coordinates__pb2._COORDINATES
_MAP.fields_by_name['maxCoordinates'].message_type = Coordinates__pb2._COORDINATES
_MAP.fields_by_name['buildings'].message_type = Building__pb2._BUILDING
DESCRIPTOR.message_types_by_name['Map'] = _MAP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Map = _reflection.GeneratedProtocolMessageType('Map', (_message.Message,), dict(
  DESCRIPTOR = _MAP,
  __module__ = 'Map_pb2'
  # @@protoc_insertion_point(class_scope:referencepoint.proto.Map)
  ))
_sym_db.RegisterMessage(Map)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
