# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Route.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Landmark_pb2 as Landmark__pb2
import Path_pb2 as Path__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Route.proto',
  package='referencepoint.proto',
  syntax='proto3',
  serialized_options=_b('\n\030com.referencepoint.proto'),
  serialized_pb=_b('\n\x0bRoute.proto\x12\x14referencepoint.proto\x1a\x0eLandmark.proto\x1a\nPath.proto\"\x8b\x01\n\x05Route\x12,\n\x04\x66rom\x18\x01 \x01(\x0b\x32\x1e.referencepoint.proto.Landmark\x12*\n\x02to\x18\x02 \x01(\x0b\x32\x1e.referencepoint.proto.Landmark\x12(\n\x04path\x18\x03 \x01(\x0b\x32\x1a.referencepoint.proto.PathB\x1a\n\x18\x63om.referencepoint.protob\x06proto3')
  ,
  dependencies=[Landmark__pb2.DESCRIPTOR,Path__pb2.DESCRIPTOR,])




_ROUTE = _descriptor.Descriptor(
  name='Route',
  full_name='referencepoint.proto.Route',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from', full_name='referencepoint.proto.Route.from', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to', full_name='referencepoint.proto.Route.to', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='referencepoint.proto.Route.path', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=205,
)

_ROUTE.fields_by_name['from'].message_type = Landmark__pb2._LANDMARK
_ROUTE.fields_by_name['to'].message_type = Landmark__pb2._LANDMARK
_ROUTE.fields_by_name['path'].message_type = Path__pb2._PATH
DESCRIPTOR.message_types_by_name['Route'] = _ROUTE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Route = _reflection.GeneratedProtocolMessageType('Route', (_message.Message,), dict(
  DESCRIPTOR = _ROUTE,
  __module__ = 'Route_pb2'
  # @@protoc_insertion_point(class_scope:referencepoint.proto.Route)
  ))
_sym_db.RegisterMessage(Route)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
