# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Step.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Particle_pb2 as Particle__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Step.proto',
  package='referencepoint.proto',
  syntax='proto3',
  serialized_options=_b('\n\030com.referencepoint.proto'),
  serialized_pb=_b('\n\nStep.proto\x12\x14referencepoint.proto\x1a\x0eParticle.proto\"g\n\x04Step\x12\x0c\n\x04time\x18\x01 \x01(\x04\x12\x0e\n\x06mean_x\x18\x02 \x01(\x01\x12\x0e\n\x06mean_y\x18\x03 \x01(\x01\x12\x31\n\tparticles\x18\x04 \x03(\x0b\x32\x1e.referencepoint.proto.ParticleB\x1a\n\x18\x63om.referencepoint.protob\x06proto3')
  ,
  dependencies=[Particle__pb2.DESCRIPTOR,])




_STEP = _descriptor.Descriptor(
  name='Step',
  full_name='referencepoint.proto.Step',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='referencepoint.proto.Step.time', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mean_x', full_name='referencepoint.proto.Step.mean_x', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mean_y', full_name='referencepoint.proto.Step.mean_y', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='particles', full_name='referencepoint.proto.Step.particles', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=155,
)

_STEP.fields_by_name['particles'].message_type = Particle__pb2._PARTICLE
DESCRIPTOR.message_types_by_name['Step'] = _STEP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Step = _reflection.GeneratedProtocolMessageType('Step', (_message.Message,), dict(
  DESCRIPTOR = _STEP,
  __module__ = 'Step_pb2'
  # @@protoc_insertion_point(class_scope:referencepoint.proto.Step)
  ))
_sym_db.RegisterMessage(Step)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
