# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Building.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Floor_pb2 as Floor__pb2
import Coordinates_pb2 as Coordinates__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Building.proto',
  package='referencepoint.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x42uilding.proto\x12\x14referencepoint.proto\x1a\x0b\x46loor.proto\x1a\x11\x43oordinates.proto\"z\n\x08\x42uilding\x12\x33\n\x08\x62oundary\x18\x01 \x03(\x0b\x32!.referencepoint.proto.Coordinates\x12\x0c\n\x04name\x18\x02 \x01(\t\x12+\n\x06\x66loors\x18\x03 \x03(\x0b\x32\x1b.referencepoint.proto.FloorB\x1a\n\x18\x63om.referencepoint.protob\x06proto3')
  ,
  dependencies=[Floor__pb2.DESCRIPTOR,Coordinates__pb2.DESCRIPTOR,])




_BUILDING = _descriptor.Descriptor(
  name='Building',
  full_name='referencepoint.proto.Building',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='boundary', full_name='referencepoint.proto.Building.boundary', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='referencepoint.proto.Building.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='floors', full_name='referencepoint.proto.Building.floors', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=194,
)

_BUILDING.fields_by_name['boundary'].message_type = Coordinates__pb2._COORDINATES
_BUILDING.fields_by_name['floors'].message_type = Floor__pb2._FLOOR
DESCRIPTOR.message_types_by_name['Building'] = _BUILDING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Building = _reflection.GeneratedProtocolMessageType('Building', (_message.Message,), dict(
  DESCRIPTOR = _BUILDING,
  __module__ = 'Building_pb2'
  # @@protoc_insertion_point(class_scope:referencepoint.proto.Building)
  ))
_sym_db.RegisterMessage(Building)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030com.referencepoint.proto'))
# @@protoc_insertion_point(module_scope)
