# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Coordinates.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Coordinates.proto',
  package='referencepoint.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x43oordinates.proto\x12\x14referencepoint.proto\"#\n\x0b\x43oordinates\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x42\x1a\n\x18\x63om.referencepoint.protob\x06proto3')
)




_COORDINATES = _descriptor.Descriptor(
  name='Coordinates',
  full_name='referencepoint.proto.Coordinates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='referencepoint.proto.Coordinates.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='referencepoint.proto.Coordinates.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['Coordinates'] = _COORDINATES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Coordinates = _reflection.GeneratedProtocolMessageType('Coordinates', (_message.Message,), dict(
  DESCRIPTOR = _COORDINATES,
  __module__ = 'Coordinates_pb2'
  # @@protoc_insertion_point(class_scope:referencepoint.proto.Coordinates)
  ))
_sym_db.RegisterMessage(Coordinates)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030com.referencepoint.proto'))
# @@protoc_insertion_point(module_scope)
