# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Floor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Landmark_pb2 as Landmark__pb2
import NavigableSpace_pb2 as NavigableSpace__pb2
import Minimap_pb2 as Minimap__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Floor.proto',
  package='referencepoint.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x46loor.proto\x12\x14referencepoint.proto\x1a\x0eLandmark.proto\x1a\x14NavigableSpace.proto\x1a\rMinimap.proto\"\xb9\x01\n\x05\x46loor\x12\x0e\n\x06number\x18\x01 \x01(\x05\x12\x31\n\tlandmarks\x18\x02 \x03(\x0b\x32\x1e.referencepoint.proto.Landmark\x12=\n\x0fnavigableSpaces\x18\x03 \x03(\x0b\x32$.referencepoint.proto.NavigableSpace\x12.\n\x07minimap\x18\x04 \x01(\x0b\x32\x1d.referencepoint.proto.MinimapB\x1a\n\x18\x63om.referencepoint.protob\x06proto3')
  ,
  dependencies=[Landmark__pb2.DESCRIPTOR,NavigableSpace__pb2.DESCRIPTOR,Minimap__pb2.DESCRIPTOR,])




_FLOOR = _descriptor.Descriptor(
  name='Floor',
  full_name='referencepoint.proto.Floor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='referencepoint.proto.Floor.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='landmarks', full_name='referencepoint.proto.Floor.landmarks', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='navigableSpaces', full_name='referencepoint.proto.Floor.navigableSpaces', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minimap', full_name='referencepoint.proto.Floor.minimap', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=276,
)

_FLOOR.fields_by_name['landmarks'].message_type = Landmark__pb2._LANDMARK
_FLOOR.fields_by_name['navigableSpaces'].message_type = NavigableSpace__pb2._NAVIGABLESPACE
_FLOOR.fields_by_name['minimap'].message_type = Minimap__pb2._MINIMAP
DESCRIPTOR.message_types_by_name['Floor'] = _FLOOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Floor = _reflection.GeneratedProtocolMessageType('Floor', (_message.Message,), dict(
  DESCRIPTOR = _FLOOR,
  __module__ = 'Floor_pb2'
  # @@protoc_insertion_point(class_scope:referencepoint.proto.Floor)
  ))
_sym_db.RegisterMessage(Floor)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030com.referencepoint.proto'))
# @@protoc_insertion_point(module_scope)
