# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Map.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Coordinates_pb2 as Coordinates__pb2
import Polygon_pb2 as Polygon__pb2
import Path_pb2 as Path__pb2
import Landmark_pb2 as Landmark__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Map.proto',
  package='referencepoint.proto',
  syntax='proto3',
  serialized_pb=_b('\n\tMap.proto\x12\x14referencepoint.proto\x1a\x11\x43oordinates.proto\x1a\rPolygon.proto\x1a\nPath.proto\x1a\x0eLandmark.proto\"\x8a\x03\n\x03Map\x12\x39\n\x0eminCoordinates\x18\x01 \x01(\x0b\x32!.referencepoint.proto.Coordinates\x12\x39\n\x0emaxCoordinates\x18\x02 \x01(\x0b\x32!.referencepoint.proto.Coordinates\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12;\n\tbuildings\x18\x05 \x03(\x0b\x32(.referencepoint.proto.Map.BuildingsEntry\x12)\n\x05paths\x18\x06 \x03(\x0b\x32\x1a.referencepoint.proto.Path\x12\x31\n\tlandmarks\x18\x07 \x03(\x0b\x32\x1e.referencepoint.proto.Landmark\x1aO\n\x0e\x42uildingsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x1d.referencepoint.proto.Polygon:\x02\x38\x01\x42\x1a\n\x18\x63om.referencepoint.protob\x06proto3')
  ,
  dependencies=[Coordinates__pb2.DESCRIPTOR,Polygon__pb2.DESCRIPTOR,Path__pb2.DESCRIPTOR,Landmark__pb2.DESCRIPTOR,])




_MAP_BUILDINGSENTRY = _descriptor.Descriptor(
  name='BuildingsEntry',
  full_name='referencepoint.proto.Map.BuildingsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='referencepoint.proto.Map.BuildingsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='referencepoint.proto.Map.BuildingsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=413,
  serialized_end=492,
)

_MAP = _descriptor.Descriptor(
  name='Map',
  full_name='referencepoint.proto.Map',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='minCoordinates', full_name='referencepoint.proto.Map.minCoordinates', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxCoordinates', full_name='referencepoint.proto.Map.maxCoordinates', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='referencepoint.proto.Map.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='referencepoint.proto.Map.description', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='buildings', full_name='referencepoint.proto.Map.buildings', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='paths', full_name='referencepoint.proto.Map.paths', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='landmarks', full_name='referencepoint.proto.Map.landmarks', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MAP_BUILDINGSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=492,
)

_MAP_BUILDINGSENTRY.fields_by_name['value'].message_type = Polygon__pb2._POLYGON
_MAP_BUILDINGSENTRY.containing_type = _MAP
_MAP.fields_by_name['minCoordinates'].message_type = Coordinates__pb2._COORDINATES
_MAP.fields_by_name['maxCoordinates'].message_type = Coordinates__pb2._COORDINATES
_MAP.fields_by_name['buildings'].message_type = _MAP_BUILDINGSENTRY
_MAP.fields_by_name['paths'].message_type = Path__pb2._PATH
_MAP.fields_by_name['landmarks'].message_type = Landmark__pb2._LANDMARK
DESCRIPTOR.message_types_by_name['Map'] = _MAP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Map = _reflection.GeneratedProtocolMessageType('Map', (_message.Message,), dict(

  BuildingsEntry = _reflection.GeneratedProtocolMessageType('BuildingsEntry', (_message.Message,), dict(
    DESCRIPTOR = _MAP_BUILDINGSENTRY,
    __module__ = 'Map_pb2'
    # @@protoc_insertion_point(class_scope:referencepoint.proto.Map.BuildingsEntry)
    ))
  ,
  DESCRIPTOR = _MAP,
  __module__ = 'Map_pb2'
  # @@protoc_insertion_point(class_scope:referencepoint.proto.Map)
  ))
_sym_db.RegisterMessage(Map)
_sym_db.RegisterMessage(Map.BuildingsEntry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030com.referencepoint.proto'))
_MAP_BUILDINGSENTRY.has_options = True
_MAP_BUILDINGSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
