# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MapService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Map_pb2 as Map__pb2
import Coordinates_pb2 as Coordinates__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='MapService.proto',
  package='referencepoint.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x10MapService.proto\x12\x14referencepoint.proto\x1a\tMap.proto\x1a\x11\x43oordinates.proto2Z\n\nMapService\x12L\n\x08ListMaps\x12!.referencepoint.proto.Coordinates\x1a\x19.referencepoint.proto.Map\"\x00\x30\x01\x42\x1a\n\x18\x63om.referencepoint.protob\x06proto3')
  ,
  dependencies=[Map__pb2.DESCRIPTOR,Coordinates__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030com.referencepoint.proto'))
# @@protoc_insertion_point(module_scope)
