# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Minimap.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Coordinates_pb2 as Coordinates__pb2
import Landmark_pb2 as Landmark__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Minimap.proto',
  package='referencepoint.proto',
  syntax='proto3',
  serialized_pb=_b('\n\rMinimap.proto\x12\x14referencepoint.proto\x1a\x11\x43oordinates.proto\x1a\x0eLandmark.proto\"\xe0\x01\n\x07Minimap\x12\x10\n\x08sideSize\x18\x01 \x01(\x01\x12\x0c\n\x04rows\x18\x02 \x01(\x05\x12\x0f\n\x07\x63olumns\x18\x03 \x01(\x05\x12\x39\n\x0eminCoordinates\x18\x04 \x01(\x0b\x32!.referencepoint.proto.Coordinates\x12\x31\n\x05tiles\x18\x05 \x03(\x0b\x32\".referencepoint.proto.Minimap.Tile\x1a\x36\n\x04Tile\x12\x0b\n\x03row\x18\x01 \x01(\x05\x12\x0e\n\x06\x63olumn\x18\x02 \x01(\x05\x12\x11\n\tlandmarks\x18\x03 \x03(\x05\x42\x1a\n\x18\x63om.referencepoint.protob\x06proto3')
  ,
  dependencies=[Coordinates__pb2.DESCRIPTOR,Landmark__pb2.DESCRIPTOR,])




_MINIMAP_TILE = _descriptor.Descriptor(
  name='Tile',
  full_name='referencepoint.proto.Minimap.Tile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='row', full_name='referencepoint.proto.Minimap.Tile.row', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='column', full_name='referencepoint.proto.Minimap.Tile.column', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='landmarks', full_name='referencepoint.proto.Minimap.Tile.landmarks', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=299,
)

_MINIMAP = _descriptor.Descriptor(
  name='Minimap',
  full_name='referencepoint.proto.Minimap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sideSize', full_name='referencepoint.proto.Minimap.sideSize', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rows', full_name='referencepoint.proto.Minimap.rows', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='columns', full_name='referencepoint.proto.Minimap.columns', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minCoordinates', full_name='referencepoint.proto.Minimap.minCoordinates', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tiles', full_name='referencepoint.proto.Minimap.tiles', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MINIMAP_TILE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=299,
)

_MINIMAP_TILE.containing_type = _MINIMAP
_MINIMAP.fields_by_name['minCoordinates'].message_type = Coordinates__pb2._COORDINATES
_MINIMAP.fields_by_name['tiles'].message_type = _MINIMAP_TILE
DESCRIPTOR.message_types_by_name['Minimap'] = _MINIMAP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Minimap = _reflection.GeneratedProtocolMessageType('Minimap', (_message.Message,), dict(

  Tile = _reflection.GeneratedProtocolMessageType('Tile', (_message.Message,), dict(
    DESCRIPTOR = _MINIMAP_TILE,
    __module__ = 'Minimap_pb2'
    # @@protoc_insertion_point(class_scope:referencepoint.proto.Minimap.Tile)
    ))
  ,
  DESCRIPTOR = _MINIMAP,
  __module__ = 'Minimap_pb2'
  # @@protoc_insertion_point(class_scope:referencepoint.proto.Minimap)
  ))
_sym_db.RegisterMessage(Minimap)
_sym_db.RegisterMessage(Minimap.Tile)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030com.referencepoint.proto'))
# @@protoc_insertion_point(module_scope)
