# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Particle.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Particle.proto',
  package='referencepoint.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x0eParticle.proto\x12\x14referencepoint.proto\"f\n\x08Particle\x12\x0c\n\x04step\x18\x01 \x01(\x01\x12\x0e\n\x06mean_x\x18\x02 \x01(\x01\x12\x0e\n\x06mean_y\x18\x03 \x01(\x01\x12\r\n\x05\x63ov_x\x18\x04 \x01(\x01\x12\x0e\n\x06\x63ov_xy\x18\x06 \x01(\x01\x12\r\n\x05\x63ov_y\x18\x05 \x01(\x01\x42\x1a\n\x18\x63om.referencepoint.protob\x06proto3')
)




_PARTICLE = _descriptor.Descriptor(
  name='Particle',
  full_name='referencepoint.proto.Particle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='step', full_name='referencepoint.proto.Particle.step', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mean_x', full_name='referencepoint.proto.Particle.mean_x', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mean_y', full_name='referencepoint.proto.Particle.mean_y', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cov_x', full_name='referencepoint.proto.Particle.cov_x', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cov_xy', full_name='referencepoint.proto.Particle.cov_xy', index=4,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cov_y', full_name='referencepoint.proto.Particle.cov_y', index=5,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=142,
)

DESCRIPTOR.message_types_by_name['Particle'] = _PARTICLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Particle = _reflection.GeneratedProtocolMessageType('Particle', (_message.Message,), dict(
  DESCRIPTOR = _PARTICLE,
  __module__ = 'Particle_pb2'
  # @@protoc_insertion_point(class_scope:referencepoint.proto.Particle)
  ))
_sym_db.RegisterMessage(Particle)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030com.referencepoint.proto'))
# @@protoc_insertion_point(module_scope)
