# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Path.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Step_pb2 as Step__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Path.proto',
  package='referencepoint.proto',
  syntax='proto3',
  serialized_pb=_b('\n\nPath.proto\x12\x14referencepoint.proto\x1a\nStep.proto\"1\n\x04Path\x12)\n\x05steps\x18\x01 \x03(\x0b\x32\x1a.referencepoint.proto.StepB\x1a\n\x18\x63om.referencepoint.protob\x06proto3')
  ,
  dependencies=[Step__pb2.DESCRIPTOR,])




_PATH = _descriptor.Descriptor(
  name='Path',
  full_name='referencepoint.proto.Path',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='steps', full_name='referencepoint.proto.Path.steps', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=97,
)

_PATH.fields_by_name['steps'].message_type = Step__pb2._STEP
DESCRIPTOR.message_types_by_name['Path'] = _PATH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Path = _reflection.GeneratedProtocolMessageType('Path', (_message.Message,), dict(
  DESCRIPTOR = _PATH,
  __module__ = 'Path_pb2'
  # @@protoc_insertion_point(class_scope:referencepoint.proto.Path)
  ))
_sym_db.RegisterMessage(Path)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030com.referencepoint.proto'))
# @@protoc_insertion_point(module_scope)
