# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Polygon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Coordinates_pb2 as Coordinates__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Polygon.proto',
  package='referencepoint.proto',
  syntax='proto3',
  serialized_pb=_b('\n\rPolygon.proto\x12\x14referencepoint.proto\x1a\x11\x43oordinates.proto\">\n\x07Polygon\x12\x33\n\x08vertices\x18\x01 \x03(\x0b\x32!.referencepoint.proto.CoordinatesB\x1a\n\x18\x63om.referencepoint.protob\x06proto3')
  ,
  dependencies=[Coordinates__pb2.DESCRIPTOR,])




_POLYGON = _descriptor.Descriptor(
  name='Polygon',
  full_name='referencepoint.proto.Polygon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vertices', full_name='referencepoint.proto.Polygon.vertices', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=120,
)

_POLYGON.fields_by_name['vertices'].message_type = Coordinates__pb2._COORDINATES
DESCRIPTOR.message_types_by_name['Polygon'] = _POLYGON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Polygon = _reflection.GeneratedProtocolMessageType('Polygon', (_message.Message,), dict(
  DESCRIPTOR = _POLYGON,
  __module__ = 'Polygon_pb2'
  # @@protoc_insertion_point(class_scope:referencepoint.proto.Polygon)
  ))
_sym_db.RegisterMessage(Polygon)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030com.referencepoint.proto'))
# @@protoc_insertion_point(module_scope)
