# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Telemetry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Route_pb2 as Route__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Telemetry.proto',
  package='referencepoint.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x0fTelemetry.proto\x12\x14referencepoint.proto\x1a\x0bRoute.proto\"\x8a\x03\n\rTelemetryData\x12,\n\x08route_id\x18\x01 \x01(\x0b\x32\x1a.referencepoint.proto.UUID\x12\x0c\n\x04time\x18\x02 \x01(\x03\x12\x0e\n\x06mean_x\x18\x03 \x01(\x01\x12\x0e\n\x06mean_y\x18\x04 \x01(\x01\x12=\n\tparticles\x18\x05 \x03(\x0b\x32*.referencepoint.proto.TelemetryData.Filter\x12\x43\n\x0b\x66ilter_type\x18\x06 \x01(\x0e\x32..referencepoint.proto.TelemetryData.FilterType\x1a\x64\n\x06\x46ilter\x12\x0c\n\x04step\x18\x01 \x01(\x01\x12\x0e\n\x06mean_x\x18\x02 \x01(\x01\x12\x0e\n\x06mean_y\x18\x03 \x01(\x01\x12\r\n\x05\x63ov_x\x18\x04 \x01(\x01\x12\x0e\n\x06\x63ov_xy\x18\x06 \x01(\x01\x12\r\n\x05\x63ov_y\x18\x05 \x01(\x01\"3\n\nFilterType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08PARTICLE\x10\x01\x12\n\n\x06KALMAN\x10\x02\"\x12\n\x04UUID\x12\n\n\x02id\x18\x01 \x01(\t\"<\n\x10TelemetrySummary\x12\x12\n\ndata_count\x18\x01 \x01(\x05\x12\x14\n\x0c\x65lapsed_time\x18\x02 \x01(\x05\x32\xb4\x01\n\tTelemetry\x12H\n\x0bRecordRoute\x12\x1b.referencepoint.proto.Route\x1a\x1a.referencepoint.proto.UUID\"\x00\x12]\n\nRecordData\x12#.referencepoint.proto.TelemetryData\x1a&.referencepoint.proto.TelemetrySummary\"\x00(\x01\x42$\n\"com.referencepoint.telemetry.protob\x06proto3')
  ,
  dependencies=[Route__pb2.DESCRIPTOR,])



_TELEMETRYDATA_FILTERTYPE = _descriptor.EnumDescriptor(
  name='FilterType',
  full_name='referencepoint.proto.TelemetryData.FilterType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PARTICLE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KALMAN', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=398,
  serialized_end=449,
)
_sym_db.RegisterEnumDescriptor(_TELEMETRYDATA_FILTERTYPE)


_TELEMETRYDATA_FILTER = _descriptor.Descriptor(
  name='Filter',
  full_name='referencepoint.proto.TelemetryData.Filter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='step', full_name='referencepoint.proto.TelemetryData.Filter.step', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mean_x', full_name='referencepoint.proto.TelemetryData.Filter.mean_x', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mean_y', full_name='referencepoint.proto.TelemetryData.Filter.mean_y', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cov_x', full_name='referencepoint.proto.TelemetryData.Filter.cov_x', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cov_xy', full_name='referencepoint.proto.TelemetryData.Filter.cov_xy', index=4,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cov_y', full_name='referencepoint.proto.TelemetryData.Filter.cov_y', index=5,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=296,
  serialized_end=396,
)

_TELEMETRYDATA = _descriptor.Descriptor(
  name='TelemetryData',
  full_name='referencepoint.proto.TelemetryData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='route_id', full_name='referencepoint.proto.TelemetryData.route_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='referencepoint.proto.TelemetryData.time', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mean_x', full_name='referencepoint.proto.TelemetryData.mean_x', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mean_y', full_name='referencepoint.proto.TelemetryData.mean_y', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='particles', full_name='referencepoint.proto.TelemetryData.particles', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='filter_type', full_name='referencepoint.proto.TelemetryData.filter_type', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TELEMETRYDATA_FILTER, ],
  enum_types=[
    _TELEMETRYDATA_FILTERTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=449,
)


_UUID = _descriptor.Descriptor(
  name='UUID',
  full_name='referencepoint.proto.UUID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='referencepoint.proto.UUID.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=451,
  serialized_end=469,
)


_TELEMETRYSUMMARY = _descriptor.Descriptor(
  name='TelemetrySummary',
  full_name='referencepoint.proto.TelemetrySummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_count', full_name='referencepoint.proto.TelemetrySummary.data_count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='elapsed_time', full_name='referencepoint.proto.TelemetrySummary.elapsed_time', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=471,
  serialized_end=531,
)

_TELEMETRYDATA_FILTER.containing_type = _TELEMETRYDATA
_TELEMETRYDATA.fields_by_name['route_id'].message_type = _UUID
_TELEMETRYDATA.fields_by_name['particles'].message_type = _TELEMETRYDATA_FILTER
_TELEMETRYDATA.fields_by_name['filter_type'].enum_type = _TELEMETRYDATA_FILTERTYPE
_TELEMETRYDATA_FILTERTYPE.containing_type = _TELEMETRYDATA
DESCRIPTOR.message_types_by_name['TelemetryData'] = _TELEMETRYDATA
DESCRIPTOR.message_types_by_name['UUID'] = _UUID
DESCRIPTOR.message_types_by_name['TelemetrySummary'] = _TELEMETRYSUMMARY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TelemetryData = _reflection.GeneratedProtocolMessageType('TelemetryData', (_message.Message,), dict(

  Filter = _reflection.GeneratedProtocolMessageType('Filter', (_message.Message,), dict(
    DESCRIPTOR = _TELEMETRYDATA_FILTER,
    __module__ = 'Telemetry_pb2'
    # @@protoc_insertion_point(class_scope:referencepoint.proto.TelemetryData.Filter)
    ))
  ,
  DESCRIPTOR = _TELEMETRYDATA,
  __module__ = 'Telemetry_pb2'
  # @@protoc_insertion_point(class_scope:referencepoint.proto.TelemetryData)
  ))
_sym_db.RegisterMessage(TelemetryData)
_sym_db.RegisterMessage(TelemetryData.Filter)

UUID = _reflection.GeneratedProtocolMessageType('UUID', (_message.Message,), dict(
  DESCRIPTOR = _UUID,
  __module__ = 'Telemetry_pb2'
  # @@protoc_insertion_point(class_scope:referencepoint.proto.UUID)
  ))
_sym_db.RegisterMessage(UUID)

TelemetrySummary = _reflection.GeneratedProtocolMessageType('TelemetrySummary', (_message.Message,), dict(
  DESCRIPTOR = _TELEMETRYSUMMARY,
  __module__ = 'Telemetry_pb2'
  # @@protoc_insertion_point(class_scope:referencepoint.proto.TelemetrySummary)
  ))
_sym_db.RegisterMessage(TelemetrySummary)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\"com.referencepoint.telemetry.proto'))
# @@protoc_insertion_point(module_scope)
